### ISSUE TITLE
Installation Procedure Issue

### ISSUE THREAD

**Issue by klou23** [BANANAPEEL202/Tank-Trouble#1]
It would be greatly appreciated if I could download this great project of yours directly through Github releases, instead of having to go to a dropbox link.

**Comment by klou23** [comment]
![Screenshot 2024-02-05 at 4 40 40 PM](https://github.com/BANANAPEEL202/Tank-Trouble/assets/58053969/7cd74c3a-ff3c-45d2-9df5-486120cbf09c)
Please see the above screenshot from the executable I downloaded in releases. This issue does not appear to be fixed.

**Comment by BANANAPEEL202** [comment]
If a .app file is not opening on your Mac, there could be several reasons for this issue. Here are some troubleshooting steps you can take:

**Check System Requirements:**

Make sure that the .app file is compatible with your version of macOS.
Some applications may require a minimum macOS version or specific hardware specifications.
App Corruption:

The .app file may be corrupt. Try downloading it again from a trusted source or reinstalling the application.
Gatekeeper Settings:

macOS has a security feature called Gatekeeper that prevents the opening of applications from unidentified developers. To override this, you can right-click on the .app file, select "Open," and then choose "Open" again in the dialog box that appears.

**File Association:**

Ensure that the .app file is associated with the correct application. Right-click on the file, choose "Get Info," and check the "Open with" section. Make sure it is set to the appropriate application.
Permissions:

Check the file permissions to ensure that your user account has the necessary privileges to open the .app file. You can do this by right-clicking on the file, selecting "Get Info," and checking the "Sharing & Permissions" section.
Log Files:

Check the Console app (found in Applications > Utilities > Console) for any error messages related to the application. This may provide insights into why the .app file is not opening.
System Updates:

Make sure that your macOS and all system software are up-to-date. Sometimes, compatibility issues are resolved with the latest updates.

**Application Support:**

Check the developer's website or support resources for any known issues or updates related to the application. There might be specific steps recommended by the developer.
If you've tried the above steps and still encounter issues, you may need to contact the application's support or the developer for further assistance. They may provide specific guidance or updates to resolve the problem.
